// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngplgbknmoewoorltnem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ncGxnYmtubW9ld29vcmx0bmVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTQyOTYsImV4cCI6MjA2NTU5MDI5Nn0.kwgyfv1080LmcOQCdtLrE6z49FoTMFLGNrxpqfSV1Ew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);